apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-recognition
  labels:
    app: image-recognition
  annotations:
    deployment.kubernetes.io/revision:  "1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: image-recognition
  strategy:
     rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
     type:  RollingUpdate
  template:
    metadata:
      labels:
        app: image-recognition
    spec:
      containers:
      - name: image-recognition
        image: amorian/image-recognition
        ports:
        - containerPort: 8080
